package deployer

import (
	"fmt"
	"io"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/user/versaDeploy/internal/config"
	verserrors "github.com/user/versaDeploy/internal/errors"
	"github.com/user/versaDeploy/internal/ssh"
)

// Services
//
// For each entry of `services`, versa writes four files to <remote_path>/.versa/:
// a wrapper script (<name>.sh) that loads the environment and execs the command, and
// a systemd unit, an OpenRC script and a SysV init script that run the wrapper. All of
// them point at <remote_path>/current, so they stay valid across deploys and
// rollbacks. The scripts below run on the server, detect its init system, copy the
// matching file into /etc only when it changed (so sudo is only needed then), enable
// it at boot and start/restart it.

// svcLayout holds the system directories the scripts touch; tests use a temp dir.
type svcLayout struct {
	etc, run, log string
}

var serverLayout = svcLayout{etc: "/etc", run: "/var/run", log: "/var/log"}

// initDetectSh sets I to systemd, openrc or sysv (SysV init, also used for upstart).
const initDetectSh = `if [ -d /run/systemd/system ]; then I=systemd
elif [ -x /sbin/openrc-run ] || [ -x /usr/sbin/openrc-run ] || [ -x /usr/bin/openrc-run ]; then I=openrc
else I=sysv; fi
`

// pathFnSh defines P, which prints a command's absolute path: from PATH, else from the
// usual sbin/bin dirs (non-root PATHs often lack /sbin). Commands run with sudo use it,
// since sudoers rules match absolute paths and old sudo (RHEL 5) has no secure_path:
// "sudo chkconfig" wouldn't match "/sbin/chkconfig". sudoersScript prints the same paths.
const pathFnSh = `P() { c=$(command -v "$1" 2>/dev/null); case "$c" in /*) echo "$c"; return ;; esac; for d in /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin; do if [ -x "$d/$1" ]; then echo "$d/$1"; return; fi; done; echo "$1"; }
`

// serviceActions are the actions `versa service` accepts.
var serviceActions = []string{"status", "start", "stop", "restart", "logs", "install", "uninstall", "sudoers"}

func q(s string) string { return ssh.ShellQuote(s) }

// sudoPrefix is prepended to commands that need root; empty when deploying as root.
// -n makes sudo fail instead of waiting for a password nobody can type.
func sudoPrefix(env *config.Environment) string {
	if env.SSH.User == "root" {
		return ""
	}
	return "sudo -n "
}

// serviceExec resolves the command a service runs; a leading "./" is relative to current.
func serviceExec(env *config.Environment, svc config.ServiceConfig, current string) (string, error) {
	if svc.Exec == "" {
		return env.DefaultServiceExec(current)
	}
	if strings.HasPrefix(svc.Exec, "./") {
		return current + svc.Exec[1:], nil
	}
	return svc.Exec, nil
}

// serviceWorkDir is the service's working directory: working_dir under current, else
// the app dir (app/<python.root> when the project is Python only).
func serviceWorkDir(env *config.Environment, svc config.ServiceConfig, current string) string {
	wd := svc.WorkingDir
	if wd == "" {
		wd = "app"
		if env.Builds.Python.Enabled && !env.Builds.Go.Enabled {
			wd = filepath.Join("app", env.Builds.Python.ProjectRoot)
		}
	}
	return strings.TrimSuffix(current+"/"+filepath.ToSlash(filepath.Clean(wd)), "/.")
}

// renderService returns the files of one service, keyed by file name in filesDir.
func renderService(project, envName string, env *config.Environment, svc config.ServiceConfig, remotePath string, l svcLayout) (map[string]string, error) {
	current := remotePath + "/current"
	filesDir := remotePath + "/.versa"
	execCmd, err := serviceExec(env, svc, current)
	if err != nil {
		return nil, fmt.Errorf("service %s: %w", svc.Name, err)
	}
	wrapper := filesDir + "/" + svc.Name + ".sh"
	envFile := ""
	if svc.EnvFile != "" {
		envFile = remotePath + "/shared/" + filepath.ToSlash(filepath.Clean(svc.EnvFile))
	}
	desc := fmt.Sprintf("%s (versaDeploy %s/%s)", svc.Name, project, envName)
	logFile := l.log + "/" + svc.Name + ".log"

	// Wrapper: same for every init system
	var w strings.Builder
	w.WriteString("#!/bin/sh\n# " + desc + ". Generated by versa on every deploy: don't edit.\n")
	w.WriteString("cd " + q(serviceWorkDir(env, svc, current)) + " || exit 1\n")
	if envFile != "" {
		// systemd loads it with EnvironmentFile (and sets VERSA_ENV_LOADED); other inits source it
		fmt.Fprintf(&w, "if [ -z \"$VERSA_ENV_LOADED\" ] && [ -f %[1]s ]; then set -a; . %[1]s; set +a; fi\n", q(envFile))
	}
	keys := make([]string, 0, len(svc.Environment))
	for k := range svc.Environment {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		w.WriteString("export " + k + "=" + q(svc.Environment[k]) + "\n")
	}
	w.WriteString("exec " + execCmd + "\n")

	// systemd unit
	var u strings.Builder
	fmt.Fprintf(&u, "# Generated by versa on every deploy: don't edit, change `services` in your deploy config.\n[Unit]\nDescription=%s\nAfter=network.target\n\n[Service]\nType=simple\nUser=%s\n", desc, svc.User)
	if envFile != "" {
		fmt.Fprintf(&u, "Environment=VERSA_ENV_LOADED=1\nEnvironmentFile=-%s\n", envFile)
	}
	fmt.Fprintf(&u, "ExecStart=/bin/sh \"%s\"\nRestart=always\nRestartSec=3\nTimeoutStopSec=%d\n\n[Install]\nWantedBy=multi-user.target\n", wrapper, stopTimeout(svc))

	// OpenRC
	openrc := fmt.Sprintf(`#!/sbin/openrc-run
# Generated by versa on every deploy: don't edit, change `+"`services`"+` in your deploy config.
description=%[1]s
command=/bin/sh
command_args=%[2]s
command_user=%[3]s
command_background=true
retry="TERM/%[7]d/KILL/5"
pidfile=%[4]s
output_log=%[5]s
error_log=%[6]s

depend() {
	need net
}
`, q(desc), q(q(wrapper)), q(svc.User), q(l.run+"/"+svc.Name+".pid"), q(logFile), q(logFile), stopTimeout(svc))

	// SysV init (RHEL/CentOS 5-6, old Debian): no supervision, pidfile + nohup
	startCmd := fmt.Sprintf("nohup /bin/sh %s >>%s 2>&1 </dev/null & echo $!", q(wrapper), q(logFile))
	sysv := fmt.Sprintf(`#!/bin/sh
# chkconfig: 2345 90 10
# description: %[1]s
### BEGIN INIT INFO
# Provides:          %[2]s
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: %[1]s
### END INIT INFO
# Generated by versa on every deploy: don't edit, change `+"`services`"+` in your deploy config.

NAME=%[3]s
RUN_AS=%[4]s
PIDFILE=%[5]s
LOGFILE=%[6]s
CMD=%[7]s
STOP_TIMEOUT=%[8]d

running() {
	[ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null
}

start() {
	if running; then
		echo "$NAME is already running (pid $(cat "$PIDFILE"))"
		return 0
	fi
	touch "$LOGFILE" && chown "$RUN_AS" "$LOGFILE" 2>/dev/null
	if [ "$(id -u)" = 0 ] && [ "$RUN_AS" != root ]; then
		pid=$(su -s /bin/sh "$RUN_AS" -c "$CMD")
	else
		pid=$(/bin/sh -c "$CMD")
	fi
	if [ -z "$pid" ]; then
		echo "failed to start $NAME"
		return 1
	fi
	echo "$pid" >"$PIDFILE"
	sleep 1
	if running; then
		echo "$NAME started (pid $pid)"
	else
		rm -f "$PIDFILE"
		echo "$NAME exited right after starting, see $LOGFILE"
		return 1
	fi
}

stop() {
	if ! running; then
		rm -f "$PIDFILE"
		echo "$NAME is not running"
		return 0
	fi
	pid=$(cat "$PIDFILE")
	kill "$pid"
	i=0
	while kill -0 "$pid" 2>/dev/null && [ "$i" -lt "$STOP_TIMEOUT" ]; do
		sleep 1
		i=$((i + 1))
	done
	kill -0 "$pid" 2>/dev/null && kill -9 "$pid"
	rm -f "$PIDFILE"
	echo "$NAME stopped"
}

case "$1" in
start) start ;;
stop) stop ;;
restart)
	stop
	start
	;;
status)
	if running; then
		echo "$NAME is running (pid $(cat "$PIDFILE"))"
	else
		echo "$NAME is not running"
		exit 3
	fi
	;;
*)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 2
	;;
esac
`, desc, svc.Name, q(svc.Name), q(svc.User), q(l.run+"/"+svc.Name+".pid"), q(logFile), q(startCmd), stopTimeout(svc))

	return map[string]string{
		svc.Name + ".sh":      w.String(),
		svc.Name + ".service": u.String(),
		svc.Name + ".openrc":  openrc,
		svc.Name + ".initd":   sysv,
	}, nil
}

// serviceScript returns the POSIX sh script that performs action on the named
// services (all when names is empty). detect is initDetectSh, or a fixed `I=...` in tests.
func serviceScript(env *config.Environment, action string, names []string, lines int, l svcLayout, detect string) string {
	if len(names) == 0 {
		for _, s := range env.Services {
			names = append(names, s.Name)
		}
	}
	S := sudoPrefix(env)
	D := env.RemotePath + "/.versa"
	var b strings.Builder
	b.WriteString(detect)
	b.WriteString(pathFnSh)
	fmt.Fprintf(&b, "S=%s\nD=%s\nETC=%s\nrc=0\n", q(S), q(D), q(l.etc))
	// $S is left unquoted on purpose: it is empty or "sudo -n "
	for _, name := range names {
		svc := findService(env, name)
		fmt.Fprintf(&b, "N=%s\n", q(name))
		switch action {
		case "install":
			b.WriteString(`case $I in
systemd)
	if ! cmp -s "$D/$N.service" "$ETC/systemd/system/$N.service"; then
		$S $(P install) -m 644 "$D/$N.service" "$ETC/systemd/system/$N.service" && $S $(P systemctl) daemon-reload || exit 1
		echo "installed $ETC/systemd/system/$N.service"
	fi
	if ! systemctl is-enabled "$N" >/dev/null 2>&1; then
		$S $(P systemctl) enable "$N" >/dev/null 2>&1 || exit 1
		echo "enabled $N at boot"
	fi
	;;
openrc)
	if ! cmp -s "$D/$N.openrc" "$ETC/init.d/$N"; then
		$S $(P install) -m 755 "$D/$N.openrc" "$ETC/init.d/$N" || exit 1
		echo "installed $ETC/init.d/$N"
	fi
	if ! rc-update show default 2>/dev/null | grep -q "^ *$N |"; then
		$S $(P rc-update) add "$N" default >/dev/null || exit 1
		echo "enabled $N at boot"
	fi
	;;
sysv)
	installed=
	if ! cmp -s "$D/$N.initd" "$ETC/init.d/$N"; then
		$S $(P install) -m 755 "$D/$N.initd" "$ETC/init.d/$N" || exit 1
		echo "installed $ETC/init.d/$N"
		installed=1
	fi
	# Checked on every run (not only on install), so a half-done install gets enabled later
	if [ -x /sbin/chkconfig ] || [ -x /usr/sbin/chkconfig ]; then
		if ! $(P chkconfig) --list "$N" 2>/dev/null | grep -q '3:on'; then
			$S $(P chkconfig) --add "$N" || exit 1
			echo "enabled $N at boot (chkconfig)"
		fi
	elif [ -x /usr/sbin/update-rc.d ] || [ -x /sbin/update-rc.d ]; then
		if ! ls "$ETC"/rc2.d/S*"$N" >/dev/null 2>&1; then
			$S $(P update-rc.d) "$N" defaults >/dev/null || exit 1
			echo "enabled $N at boot (update-rc.d)"
		fi
	elif [ -n "$installed" ]; then
		echo "WARNING: neither chkconfig nor update-rc.d found: enable $N at boot by hand"
	fi
	;;
esac
`)
		case "start", "stop", "restart":
			fmt.Fprintf(&b, `case $I in
systemd) $S $(P systemctl) %[1]s "$N" || rc=1 ;;
openrc) $S $(P rc-service) "$N" %[1]s || rc=1 ;;
sysv) $S "$ETC/init.d/$N" %[1]s || rc=1 ;;
esac
`, action)
			if action != "stop" {
				wait := 3
				if svc != nil && svc.StartWait > 0 {
					wait = svc.StartWait
				}
				// Confirm it is still up after start_wait seconds (crash loops show up as inactive)
				fmt.Fprintf(&b, `sleep %d
case $I in
systemd) systemctl is-active --quiet "$N" || { echo "$N is not running:"; systemctl status "$N" --no-pager -n 20 2>&1; rc=1; } ;;
openrc) $S $(P rc-service) "$N" status >/dev/null 2>&1 || { echo "$N is not running:"; tail -n 20 %[2]s; rc=1; } ;;
sysv) $S "$ETC/init.d/$N" status >/dev/null 2>&1 || { echo "$N is not running:"; tail -n 20 %[2]s; rc=1; } ;;
esac
`, wait, q(l.log+"/"+name+".log"))
			}
		case "status":
			b.WriteString(`case $I in
systemd) systemctl status "$N" --no-pager -n 10 2>&1 || rc=1 ;;
openrc) $S $(P rc-service) "$N" status || rc=1 ;;
sysv) $S "$ETC/init.d/$N" status || rc=1 ;;
esac
`)
		case "logs":
			fmt.Fprintf(&b, `case $I in
systemd) $S $(P journalctl) -u "$N" -n %[1]d -f --no-pager ;;
*) tail -n %[1]d -f %[2]s ;;
esac
`, lines, q(l.log+"/"+name+".log"))
		case "uninstall":
			b.WriteString(`case $I in
systemd)
	$S $(P systemctl) stop "$N" 2>/dev/null
	$S $(P systemctl) disable "$N" >/dev/null 2>&1
	$S $(P rm) -f "$ETC/systemd/system/$N.service" && $S $(P systemctl) daemon-reload || rc=1
	;;
openrc)
	$S $(P rc-service) "$N" stop 2>/dev/null
	$S $(P rc-update) del "$N" default >/dev/null 2>&1
	$S $(P rm) -f "$ETC/init.d/$N" || rc=1
	;;
sysv)
	$S "$ETC/init.d/$N" stop 2>/dev/null
	if [ -x /sbin/chkconfig ] || [ -x /usr/sbin/chkconfig ]; then $S $(P chkconfig) --del "$N"; elif [ -x /usr/sbin/update-rc.d ]; then $S $(P update-rc.d) -f "$N" remove >/dev/null; fi
	$S $(P rm) -f "$ETC/init.d/$N" || rc=1
	;;
esac
echo "removed $N"
`)
		}
	}
	b.WriteString("exit $rc\n")
	return b.String()
}

// stopTimeout is how long a stop waits for the process to exit before SIGKILL.
func stopTimeout(s config.ServiceConfig) int {
	if s.StopTimeout > 0 {
		return s.StopTimeout
	}
	return 30
}

func findService(env *config.Environment, name string) *config.ServiceConfig {
	for i := range env.Services {
		if env.Services[i].Name == name {
			return &env.Services[i]
		}
	}
	return nil
}

// sudoersScript prints the sudoers lines the deploy user needs, with the binary paths
// of this server (sudoers only matches full paths).
func sudoersScript(env *config.Environment, project string) string {
	var b strings.Builder
	b.WriteString(initDetectSh)
	b.WriteString(pathFnSh)
	fmt.Fprintf(&b, "U=%s\nD=%s\n", q(env.SSH.User), q(env.RemotePath+"/.versa"))
	// Old sudo (RHEL/CentOS 5) has no /etc/sudoers.d: the lines go in /etc/sudoers itself
	fmt.Fprintf(&b, `if [ -d /etc/sudoers.d ]; then echo "# versa services for %[1]s. Save with: sudo visudo -f /etc/sudoers.d/versa-%[2]s"
else echo "# versa services for %[1]s. This server has no /etc/sudoers.d: add these lines at the end of /etc/sudoers with: visudo (as root)"; fi
`, strings.ReplaceAll(project, `"`, ""), sanitizeFileName(project))
	// RHEL/CentOS <= 7 ship "Defaults requiretty", which makes sudo refuse to run over
	// ssh without a terminal (how versa runs commands)
	b.WriteString("echo \"Defaults:$U !requiretty\"\n")
	for _, s := range env.Services {
		fmt.Fprintf(&b, "N=%s\n", q(s.Name))
		b.WriteString(`IN=$(P install); RM=$(P rm)
case $I in
systemd) SC=$(P systemctl); JC=$(P journalctl)
	echo "$U ALL=(root) NOPASSWD: $SC start $N, $SC stop $N, $SC restart $N, $SC enable $N, $SC disable $N, $SC daemon-reload, $JC -u $N *, $IN -m 644 $D/$N.service /etc/systemd/system/$N.service, $RM -f /etc/systemd/system/$N.service" ;;
openrc) RS=$(P rc-service); RU=$(P rc-update)
	echo "$U ALL=(root) NOPASSWD: $RS $N *, $RU add $N default, $RU del $N default, $IN -m 755 $D/$N.openrc /etc/init.d/$N, $RM -f /etc/init.d/$N" ;;
sysv)
	if [ -x /sbin/chkconfig ] || [ -x /usr/sbin/chkconfig ]; then CK=$(P chkconfig); EN="$CK --add $N, $CK --del $N"; else UR=$(P update-rc.d); EN="$UR $N defaults, $UR -f $N remove"; fi
	echo "$U ALL=(root) NOPASSWD: /etc/init.d/$N *, $EN, $IN -m 755 $D/$N.initd /etc/init.d/$N, $RM -f /etc/init.d/$N" ;;
esac
`)
	}
	return b.String()
}

// sudoCheckScript prints "ok <name>" or "missing <name>" per service, depending on
// whether the deploy user may run with passwordless sudo what the next deploy needs:
// installing the service when it isn't installed yet, else restarting it. (sudo -l
// can't vouch for a command that doesn't exist, like a not yet installed init script.)
func sudoCheckScript(env *config.Environment) string {
	var b strings.Builder
	b.WriteString(initDetectSh)
	b.WriteString(pathFnSh)
	fmt.Fprintf(&b, "D=%s\n", q(env.RemotePath+"/.versa"))
	for _, s := range env.Services {
		fmt.Fprintf(&b, "N=%s\n", q(s.Name))
		b.WriteString(`case $I in
systemd) T="/etc/systemd/system/$N.service"; R="$(P systemctl) restart $N"; C="$(P install) -m 644 $D/$N.service $T" ;;
openrc) T="/etc/init.d/$N"; R="$(P rc-service) $N restart"; C="$(P install) -m 755 $D/$N.openrc $T" ;;
sysv) T="/etc/init.d/$N"; R="$T restart"; C="$(P install) -m 755 $D/$N.initd $T" ;;
esac
[ -e "$T" ] && C=$R
if sudo -n -l $C >/dev/null 2>&1; then echo "ok $N"; else echo "missing $N"; fi
`)
	}
	return b.String()
}

func sanitizeFileName(s string) string {
	return strings.Map(func(r rune) rune {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '-' || r == '_' {
			return r
		}
		return '-'
	}, s)
}

// shCmd runs a POSIX script regardless of the remote user's login shell.
func shCmd(script string) string {
	return "/bin/sh -c " + q(script)
}

// ServiceRestartCommands returns the remote commands that restart (and verify) every
// service of env; used after rollbacks done outside the Deployer (TUI).
func ServiceRestartCommands(env *config.Environment) []string {
	if len(env.Services) == 0 {
		return nil
	}
	return []string{shCmd(serviceScript(env, "restart", nil, 0, serverLayout, initDetectSh))}
}

// ServiceSudoCheck reports the services the deploy user can't restart with
// passwordless sudo (nil when deploying as root or there are no services).
func ServiceSudoCheck(c *ssh.Client, env *config.Environment) ([]string, error) {
	if len(env.Services) == 0 || env.SSH.User == "root" {
		return nil, nil
	}
	out, err := c.ExecuteCommand(sudoCheckScript(env))
	if err != nil {
		return nil, err
	}
	var missing []string
	for _, line := range strings.Split(strings.TrimSpace(out), "\n") {
		if name, ok := strings.CutPrefix(line, "missing "); ok {
			missing = append(missing, name)
		}
	}
	return missing, nil
}

// writeServiceFiles uploads the generated files of every service to <remote_path>/.versa.
func (d *Deployer) writeServiceFiles(c *ssh.Client) error {
	dir := d.remote(".versa")
	if err := c.MkdirAll(dir); err != nil {
		return err
	}
	for _, svc := range d.env.Services {
		files, err := renderService(d.cfg.Project, d.envName, d.env, svc, d.env.RemotePath, serverLayout)
		if err != nil {
			return err
		}
		for name, content := range files {
			if err := c.WriteRemoteBytes(dir+"/"+name, []byte(content)); err != nil {
				return fmt.Errorf("failed to write %s: %w", name, err)
			}
		}
	}
	return nil
}

// runServiceAction runs action on the named services (all when empty) and logs its output.
func (d *Deployer) runServiceAction(c *ssh.Client, action string, names []string) error {
	out, err := c.ExecuteCommandWithTimeout(shCmd(serviceScript(d.env, action, names, 0, serverLayout, initDetectSh)), d.serviceTimeout())
	for _, line := range strings.Split(strings.TrimSpace(out), "\n") {
		if line != "" {
			d.log.Info("  %s", line)
		}
	}
	if err != nil {
		if action == "status" {
			return fmt.Errorf("not every service is running")
		}
		// sudo's complaint arrives on stderr, which the ssh client puts in err
		if strings.Contains(out+err.Error(), "sudo:") {
			return verserrors.New(verserrors.CodeDeploymentFailed, fmt.Sprintf("service %s failed: the deploy user needs passwordless sudo", action),
				fmt.Sprintf("Run 'versa service %s sudoers' and add the printed lines on the server (the output says where).", d.envName), err)
		}
		return fmt.Errorf("service %s failed: %w", action, err)
	}
	return nil
}

func (d *Deployer) serviceTimeout() time.Duration {
	wait := 0
	for _, s := range d.env.Services {
		wait += stopTimeout(s) + s.StartWait + 15 // stop + start + check
	}
	return time.Duration(wait+30) * time.Second
}

// activateServices installs/updates every service and restarts it, failing if one
// doesn't stay up. Runs after the symlink switch and post_deploy hooks.
func (d *Deployer) activateServices(c *ssh.Client) error {
	if len(d.env.Services) == 0 {
		return nil
	}
	d.log.Info("Updating services...")
	if err := d.writeServiceFiles(c); err != nil {
		return err
	}
	if err := d.runServiceAction(c, "install", nil); err != nil {
		return err
	}
	d.log.Info("Restarting services...")
	return d.runServiceAction(c, "restart", nil)
}

// afterRollback runs what a release switch needs once current points back to an older
// release: services_reload and a restart of the services. Failures are warnings.
func (d *Deployer) afterRollback(c *ssh.Client) {
	d.executeServicesReload(c)
	if len(d.env.Services) == 0 {
		return
	}
	d.log.Info("Restarting services...")
	if err := d.runServiceAction(c, "restart", nil); err != nil {
		d.log.Warn("Service restart after rollback failed: %v", err)
	}
}

// ServiceAction runs `versa service <env> <action>` on the named service (all when
// name is empty). logs streams to out until interrupted; sudoers prints the lines.
func (d *Deployer) ServiceAction(action, name string, lines int, out io.Writer) error {
	if d.env.Local {
		return errLocalUnsupported("service")
	}
	if len(d.env.Services) == 0 {
		return fmt.Errorf("environment %s has no services: add a 'services' section to its config", d.envName)
	}
	valid := false
	for _, a := range serviceActions {
		valid = valid || a == action
	}
	if !valid {
		return fmt.Errorf("unknown action %q (use %s)", action, strings.Join(serviceActions, ", "))
	}
	var names []string
	if name != "" {
		if findService(d.env, name) == nil {
			return fmt.Errorf("service %q is not defined in environment %s", name, d.envName)
		}
		names = []string{name}
	}
	if action == "logs" && len(names) == 0 {
		if len(d.env.Services) > 1 {
			return fmt.Errorf("environment %s has several services: choose one with --name", d.envName)
		}
		names = []string{d.env.Services[0].Name}
	}

	c, err := ssh.NewClient(&d.env.SSH, d.log)
	if err != nil {
		return verserrors.Wrap(err)
	}
	defer c.Close()

	switch action {
	case "logs":
		return c.ExecuteCommandStreaming(shCmd(serviceScript(d.env, "logs", names, lines, serverLayout, initDetectSh)), out, out)
	case "sudoers":
		text, err := c.ExecuteCommand(sudoersScript(d.env, d.cfg.Project))
		fmt.Fprint(out, text)
		return err
	case "install":
		if err := d.writeServiceFiles(c); err != nil {
			return err
		}
	}
	return d.runServiceAction(c, action, names)
}
